# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:00
from __future__ import unicode_literals

from django.db import migrations
from employees.models import Employee, Departament

def add_departaments(apps, schema_editor):
    departament = Departament(name='Отдел разработки')
    departament.save()
    departament = Departament(name='Отдел сопровождения')
    departament.save()
    departament = Departament(name='Отдел исследований')
    departament.save()

def add_employees(apps, schema_editor):
    departament1 = Departament.objects.get(name__iexact='Отдел разработки')
    departament2 = Departament.objects.get(name__iexact='Отдел сопровождения')
    departament3 = Departament.objects.get(name__iexact='Отдел исследований')
    employee = Employee(name='Вячеслав',surname='Абрамов',patronymic='Владимирович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Владислав',surname='Авдеев',patronymic='Денисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Валентин',surname='Агафонов',patronymic='Викторович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Даниил',surname='Аксёнов',patronymic='Вячеславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Пётр',surname='Александров',patronymic='Кириллович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Артём',surname='Алексеев',patronymic='Георгиевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Глеб',surname='Андреев',patronymic='Геннадьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Сергей',surname='Анисимов',patronymic='Олегович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Валерий',surname='Антонов',patronymic='Филиппович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Роман',surname='Артемьев',patronymic='Данилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Яков',surname='Архипов',patronymic='Григорьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Семён',surname='Афанасьев',patronymic='Юрьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Григорий',surname='Баранов',patronymic='Вадимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Валентин',surname='Белов',patronymic='Семёнович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Ростислав',surname='Белозёров',patronymic='Юрьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Геннадий',surname='Белоусов',patronymic='Иннокентьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Александр',surname='Беляков',patronymic='Артёмович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Игорь',surname='Беспалов',patronymic='Богданович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Вячеслав',surname='Бирюков',patronymic='Святославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Роман',surname='Блинов',patronymic='Русланович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Валерий',surname='Блохин',patronymic='Георгиевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Андрей',surname='Бобров',patronymic='Семёнович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Валентин',surname='Бобылёв',patronymic='Филиппович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Геннадий',surname='Богданов',patronymic='Тимурович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Михаил',surname='Большаков',patronymic='Фёдорович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Вадим',surname='Борисов',patronymic='Богданович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Игорь',surname='Брагин',patronymic='Аркадьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Василий',surname='Буров',patronymic='Петрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Владимир',surname='Веселов',patronymic='Станиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Тимофей',surname='Вишняков',patronymic='Ростиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Никита',surname='Владимиров',patronymic='Иванович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Артём',surname='Власов',patronymic='Вадимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Руслан',surname='Воробьёв',patronymic='Никитич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Эдуард',surname='Воронов',patronymic='Игоревич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Борис',surname='Воронцов',patronymic='Артёмович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Виктор',surname='Герасимов',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Алексей',surname='Горбачёв',patronymic='Святославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Виталий',surname='Гордеев',patronymic='Александрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Евгений',surname='Горшков',patronymic='Вадимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Аркадий',surname='Григорьев',patronymic='Владимирович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Владислав',surname='Гришин',patronymic='Святославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Павел',surname='Громов',patronymic='Дмитриевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Яков',surname='Гуляев',patronymic='Анатольевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Кирилл',surname='Гурьев',patronymic='Ростиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Иван',surname='Гусев',patronymic='Николаевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Виталий',surname='Гущин',patronymic='Вадимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Сергей',surname='Давыдов',patronymic='Анатольевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Илья',surname='Данилов',patronymic='Яковлевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Егор',surname='Дементьев',patronymic='Петрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Иван',surname='Дмитриев',patronymic='Даниилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Валентин',surname='Доронин',patronymic='Ярославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Тимофей',surname='Дорофеев',patronymic='Глебович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Ростислав',surname='Дроздов',patronymic='Владимирович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Матвей',surname='Дьячков',patronymic='Борисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Леонид',surname='Евдокимов',patronymic='Васильевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Глеб',surname='Евсеев',patronymic='Матвеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Иван',surname='Егоров',patronymic='Русланович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Станислав',surname='Елисеев',patronymic='Игоревич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Аркадий',surname='Ермаков',patronymic='Яковлевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Богдан',surname='Ершов',patronymic='Борисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Фёдор',surname='Ефремов',patronymic='Леонидович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Тимур',surname='Жданов',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Николай',surname='Журавлёв',patronymic='Святославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Кирилл',surname='Захаров',patronymic='Даниилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Антон',surname='Зимин',patronymic='Ярославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Антон',surname='Зиновьев',patronymic='Антонович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Даниил',surname='Зуев',patronymic='Глебович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Максим',surname='Зыков',patronymic='Михайлович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Никита',surname='Иванов',patronymic='Эдуардович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Филипп',surname='Игнатов',patronymic='Петрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Игорь',surname='Игнатьев',patronymic='Данилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Виталий',surname='Ильин',patronymic='Александрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Максим',surname='Исаев',patronymic='Кириллович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Тимофей',surname='Исаков',patronymic='Валерьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Валентин',surname='Кабанов',patronymic='Данилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Игорь',surname='Казаков',patronymic='Леонидович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Станислав',surname='Калашников',patronymic='Алексеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Роман',surname='Капустин',patronymic='Александрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Никита',surname='Кириллов',patronymic='Романович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Игорь',surname='Киселёв',patronymic='Иннокентьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Ярослав',surname='Князев',patronymic='Эдуардович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Антон',surname='Ковалёв',patronymic='Андреевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Денис',surname='Колесников',patronymic='Матвеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Виталий',surname='Колобов',patronymic='Валентинович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Борис',surname='Комиссаров',patronymic='Аркадьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Андрей',surname='Кондратьев',patronymic='Андреевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Даниил',surname='Коновалов',patronymic='Иннокентьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Даниил',surname='Кононов',patronymic='Денисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Матвей',surname='Константинов',patronymic='Евгеньевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Павел',surname='Копылов',patronymic='Ильич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Николай',surname='Корнилов',patronymic='Дмитриевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Аркадий',surname='Королёв',patronymic='Богданович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Сергей',surname='Костин',patronymic='Викторович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Иннокентий',surname='Котов',patronymic='Сергеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Александр',surname='Кошелев',patronymic='Антонович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Эдуард',surname='Красильников',patronymic='Вячеславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Егор',surname='Крылов',patronymic='Фёдорович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Александр',surname='Крюков',patronymic='Никитич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Павел',surname='Кудрявцев',patronymic='Артёмович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Эдуард',surname='Кузнецов',patronymic='Вадимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Степан',surname='Кузьмин',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Дмитрий',surname='Кулагин',patronymic='Дмитриевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Гавриил',surname='Кулаков',patronymic='Филиппович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Николай',surname='Куликов',patronymic='Фёдорович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Дмитрий',surname='Лаврентьев',patronymic='Александрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Борис',surname='Лазарев',patronymic='Семёнович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Лев',surname='Лапин',patronymic='Львович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Матвей',surname='Ларионов',patronymic='Иванович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Николай',surname='Лихачёв',patronymic='Филиппович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Святослав',surname='Лобанов',patronymic='Олегович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Глеб',surname='Логинов',patronymic='Максимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Вадим',surname='Лукин',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Юрий',surname='Лыткин',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Сергей',surname='Макаров',patronymic='Петрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Георгий',surname='Максимов',patronymic='Данилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Матвей',surname='Мамонтов',patronymic='Ярославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Леонид',surname='Марков',patronymic='Витальевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Валерий',surname='Матвеев',patronymic='Юрьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Роман',surname='Мельников',patronymic='Яковлевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Кирилл',surname='Меркушев',patronymic='Станиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Богдан',surname='Миронов',patronymic='Владимирович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Борис',surname='Мишин',patronymic='Олегович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Лев',surname='Моисеев',patronymic='Ростиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Святослав',surname='Молчанов',patronymic='Львович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Степан',surname='Морозов',patronymic='Станиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Геннадий',surname='Муравьёв',patronymic='Артёмович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Лев',surname='Мухин',patronymic='Петрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Богдан',surname='Мясников',patronymic='Егорович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Иннокентий',surname='Наумов',patronymic='Юрьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Яков',surname='Некрасов',patronymic='Павлович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Вячеслав',surname='Нестеров',patronymic='Филиппович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Егор',surname='Никитин',patronymic='Филиппович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Святослав',surname='Никифоров',patronymic='Вадимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Василий',surname='Николаев',patronymic='Артёмович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Даниил',surname='Никонов',patronymic='Данилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Тимофей',surname='Новиков',patronymic='Сергеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Ростислав',surname='Носков',patronymic='Ярославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Виктор',surname='Носов',patronymic='Денисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Дмитрий',surname='Овчинников',patronymic='Вячеславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Николай',surname='Одинцов',patronymic='Сергеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Андрей',surname='Орехов',patronymic='Михайлович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Филипп',surname='Осипов',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Максим',surname='Павлов',patronymic='Богданович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Леонид',surname='Панов',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Анатолий',surname='Панфилов',patronymic='Григорьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Сергей',surname='Пахомов',patronymic='Павлович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Иван',surname='Пестов',patronymic='Матвеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Евгений',surname='Петров',patronymic='Сергеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Егор',surname='Пономарёв',patronymic='Львович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Даниил',surname='Потапов',patronymic='Денисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Филипп',surname='Прохоров',patronymic='Юрьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Сергей',surname='Рогов',patronymic='Викторович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Тимофей',surname='Родионов',patronymic='Богданович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Валентин',surname='Рожков',patronymic='Сергеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Лев',surname='Романов',patronymic='Андреевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Валерий',surname='Русаков',patronymic='Даниилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Артём',surname='Рыбаков',patronymic='Павлович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()
    employee = Employee(name='Алексей',surname='Рябов',patronymic='Анатольевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Денис',surname='Савин',patronymic='Яковлевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Ярослав',surname='Сазонов',patronymic='Ростиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Данила',surname='Самойлов',patronymic='Владимирович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Яков',surname='Самсонов',patronymic='Владимирович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Георгий',surname='Сафонов',patronymic='Денисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Эдуард',surname='Селиверстов',patronymic='Валентинович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Денис',surname='Семёнов',patronymic='Степанович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Владимир',surname='Сергеев',patronymic='Фёдорович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Леонид',surname='Сидоров',patronymic='Яковлевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Богдан',surname='Силин',patronymic='Эдуардович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Гавриил',surname='Симонов',patronymic='Гавриилович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Кирилл',surname='Ситников',patronymic='Вячеславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Владислав',surname='Смирнов',patronymic='Фёдорович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Александр',surname='Соболев',patronymic='Никитич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Иннокентий',surname='Сорокин',patronymic='Николаевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Анатолий',surname='Степанов',patronymic='Русланович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Евгений',surname='Стрелков',patronymic='Георгиевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Игорь',surname='Субботин',patronymic='Николаевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Святослав',surname='Суханов',patronymic='Александрович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Михаил',surname='Сысоев',patronymic='Максимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Эдуард',surname='Тарасов',patronymic='Романович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Михаил',surname='Терентьев',patronymic='Святославович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Геннадий',surname='Тетерин',patronymic='Антонович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Сергей',surname='Тимофеев',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Станислав',surname='Титов',patronymic='Леонидович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament2)
    employee.save()
    employee = Employee(name='Илья',surname='Тихонов',patronymic='Олегович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Алексей',surname='Трофимов',patronymic='Георгиевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Иван',surname='Туров',patronymic='Валентинович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Тимофей',surname='Уваров',patronymic='Филиппович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Богдан',surname='Устинов',patronymic='Николаевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Антон',surname='Фадеев',patronymic='Тимофеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament1)
    employee.save()
    employee = Employee(name='Пётр',surname='Федосеев',patronymic='Богданович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament3)
    employee.save()
    employee = Employee(name='Ростислав',surname='Федотов',patronymic='Егорович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament3)
    employee.save()
    employee = Employee(name='Степан',surname='Филатов',patronymic='Олегович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Виктор',surname='Филиппов',patronymic='Юрьевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Никита',surname='Фокин',patronymic='Вадимович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament3)
    employee.save()
    employee = Employee(name='Вадим',surname='Фомин',patronymic='Борисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Святослав',surname='Фомичёв',patronymic='Николаевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament2)
    employee.save()
    employee = Employee(name='Руслан',surname='Харитонов',patronymic='Вячеславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Виталий',surname='Хохлов',patronymic='Глебович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Алексей',surname='Цветков',patronymic='Тимурович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Ярослав',surname='Шарапов',patronymic='Степанович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Виктор',surname='Шаров',patronymic='Леонидович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Лев',surname='Шашков',patronymic='Сергеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament1)
    employee.save()
    employee = Employee(name='Роман',surname='Шестаков',patronymic='Владиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Даниил',surname='Шилов',patronymic='Игоревич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Виктор',surname='Ширяев',patronymic='Владимирович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament3)
    employee.save()
    employee = Employee(name='Иннокентий',surname='Шубин',patronymic='Никитич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Павел',surname='Щербаков',patronymic='Денисович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='менеджер',departament=departament2)
    employee.save()
    employee = Employee(name='Алексей',surname='Щукин',patronymic='Фёдорович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Руслан',surname='Юдин',patronymic='Владиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='ученый',departament=departament1)
    employee.save()
    employee = Employee(name='Фёдор',surname='Яковлев',patronymic='Алексеевич',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='тестировщик',departament=departament1)
    employee.save()
    employee = Employee(name='Владимир',surname='Якушев',patronymic='Станиславович',
        birthday='1990-01-01',email='mail@mail.dev',phone='+70123456789',
        start_working_date='2011-01-01',position='разработчик',departament=departament2)
    employee.save()



class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_departaments),
        migrations.RunPython(add_employees),
    ]
